# Handling Reading
exclude:
- README.md
- LICENSE
- Gemfile*
encoding: utf-8

# Plugins
gems:
- jekyll-github-metadata
- jekyll-seo-tag
- jekyll-sitemap

# Conversion
markdown: kramdown
highlighter: rouge

# Output Configuration
permalink: pretty
timezone: America/Lima

# Defaults
defaults:
-
  scope:
    path: ''
    type: posts
  values:
    layout: presentation
    kind: presentation

# Site Settings
title: Talleres UNC
description: >
  Contenido compartido y usado en los talleres de programación y hacking que
  imparto en Ingeniería de Sistemas de la Universidad Nacional de Cajamarca.
url: https://talleres.bryanjhv.xyz
author: bryanjhv
repository: bryanjhv/talleres
