# Site settings
title: Taller UNC
description: >
  Contenido compartido y usado en el taller de programación y hacking que
  imparto en la E.A.P. Ingeniería de Sistemas de la Universidad Nacional de
  Cajamarca.
url: https://talleres.bryanjhv.xyz
repo: https://github.com/bryanjhv/talleres
permalink: /:year/:month/:day/
local: false

# Parsing options
encoding: utf-8
timezone: America/Lima
exclude: [README.md, LICENSE, Gemfile*]

# Defaults
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: presentation
      kind: presentation
